import type { Evento } from './evento';

// PROVISÓRIO. Os 8 eventos do dados/eventos.json da entrega 1, agora como
// constante tipada. Na aula 07 eles voltam a vir por HTTP (httpResource) e
// este arquivo morre — por isso o JSON também foi para public/dados/.
export const EVENTOS: readonly Evento[] = [
  {
    id: '1',
    slug: 'react-recife-meetup-42',
    titulo: 'React Recife · Meetup #42',
    resumo: 'Uma noite sobre Signals e o futuro da reatividade.',
    descricao:
      'Duas palestras curtas e uma roda de conversa sobre como signals estão mudando React, Angular e Solid.',
    organizador: 'React Recife',
    organizadorSlug: 'react-recife',
    categoria: 'Front-end',
    formato: 'Presencial',
    cidade: 'Recife',
    inicioEm: '2026-10-08T19:00',
    duracaoMin: 150,
    gratuito: true,
    vagas: 80,
    nivel: 'Intermediário',
  },
  {
    id: '2',
    slug: 'angular-na-pratica-signal-forms',
    titulo: 'Angular na Prática · Signal Forms',
    resumo: 'Live coding construindo formulários com Signal Forms do zero.',
    descricao:
      'Uma sessão online mostrando como migrar formulários reativos para Signal Forms, com validação por schema e acesso tipado aos campos.',
    organizador: 'Angular Brasil',
    organizadorSlug: 'angular-brasil',
    categoria: 'Front-end',
    formato: 'Online',
    inicioEm: '2026-10-14T20:00',
    duracaoMin: 90,
    gratuito: true,
    vagas: null,
    nivel: 'Intermediário',
  },
  {
    id: '3',
    slug: 'workshop-acessibilidade-web',
    titulo: 'Workshop de Acessibilidade Web',
    resumo: 'WCAG, leitores de tela e testes com AXE, mão na massa.',
    descricao:
      'Um workshop de meio período para auditar e corrigir uma aplicação real: contraste, foco, ARIA e navegação por teclado.',
    organizador: 'A11y Nordeste',
    organizadorSlug: 'a11y-nordeste',
    categoria: 'Acessibilidade',
    formato: 'Presencial',
    cidade: 'Recife',
    inicioEm: '2026-10-18T09:00',
    duracaoMin: 240,
    gratuito: false,
    vagas: 30,
    nivel: 'Iniciante',
  },
  {
    id: '4',
    slug: 'typescript-avancado-tipos-que-trabalham',
    titulo: 'TypeScript Avançado · Tipos que Trabalham por Você',
    resumo: 'Tipos condicionais, template literal types e inferência.',
    descricao:
      'Palestra e exercícios guiados sobre como usar o sistema de tipos do TypeScript para eliminar classes inteiras de bugs.',
    organizador: 'TS Recife',
    organizadorSlug: 'ts-recife',
    categoria: 'Linguagens',
    formato: 'Híbrido',
    cidade: 'Recife',
    inicioEm: '2026-10-22T19:30',
    duracaoMin: 120,
    gratuito: true,
    vagas: 50,
    nivel: 'Avançado',
  },
  {
    id: '5',
    slug: 'design-systems-do-figma-ao-codigo',
    titulo: 'Design Systems: do Figma ao Código',
    resumo: 'Como designers e devs mantêm um design system vivo.',
    descricao:
      'Um bate-papo entre times de design e engenharia sobre tokens, componentes compartilhados e versionamento de bibliotecas de UI.',
    organizador: 'UX Pernambuco',
    organizadorSlug: 'ux-pernambuco',
    categoria: 'Design',
    formato: 'Presencial',
    cidade: 'Olinda',
    inicioEm: '2026-10-29T18:30',
    duracaoMin: 120,
    gratuito: true,
    vagas: 60,
    nivel: 'Iniciante',
  },
  {
    id: '6',
    slug: 'node-em-producao',
    titulo: 'Node.js em Produção',
    resumo: 'Observabilidade, filas e deploy sem sustos.',
    descricao:
      'Casos reais de APIs Node.js rodando em escala: logs estruturados, métricas, tratamento de erros e estratégias de deploy.',
    organizador: 'Node PE',
    organizadorSlug: 'node-pe',
    categoria: 'Back-end',
    formato: 'Online',
    inicioEm: '2026-11-05T19:00',
    duracaoMin: 100,
    gratuito: true,
    vagas: null,
    nivel: 'Intermediário',
  },
  {
    id: '7',
    slug: 'hackathon-cidades-inteligentes',
    titulo: 'Hackathon Cidades Inteligentes',
    resumo: '24 horas criando soluções para a mobilidade urbana.',
    descricao:
      'Times multidisciplinares usam dados abertos da prefeitura para prototipar soluções de mobilidade. Premiação para os três primeiros.',
    organizador: 'Porto Digital',
    organizadorSlug: 'porto-digital',
    categoria: 'Hackathon',
    formato: 'Presencial',
    cidade: 'Recife',
    inicioEm: '2026-11-14T09:00',
    duracaoMin: 1440,
    gratuito: true,
    vagas: 120,
    nivel: 'Intermediário',
  },
  {
    id: '8',
    slug: 'testes-e2e-com-playwright',
    titulo: 'Testes E2E com Playwright',
    resumo: 'Do primeiro teste ao pipeline de CI em uma noite.',
    descricao:
      'Workshop prático cobrindo seletores acessíveis, fixtures, testes visuais e integração do Playwright com GitHub Actions.',
    organizador: 'QA Recife',
    organizadorSlug: 'qa-recife',
    categoria: 'Qualidade',
    formato: 'Híbrido',
    cidade: 'Caruaru',
    inicioEm: '2026-11-19T19:00',
    duracaoMin: 180,
    gratuito: false,
    vagas: 40,
    nivel: 'Avançado',
  },
];
